### ISSUE TITLE
Tracking: dependencies to update

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/polkadot#126]
Additionally to https://github.com/paritytech/substrate/issues/808 we have the following dependencies we might want to upgrade sooner or later:

- [ ]  `libsecp256k1 0.2.2` causes:
    - [ ] `sha2 0.6.0` ([latest is `0.8.0`](https://docs.rs/crate/sha2/)) -> `block-buffer 0.2.0`, `byte-tools 0.2.0`
    - [ ]  `hmac-drbg 0.1.2`-> `hmac 0.4.2` (latest is `0.6.3`) -> `crypto-mac 0.4.0` -> `generic-array 0.8.3`, `subtle 1.0.0`
- [ ] kvdb & kvdb-rocksdb: We are currently using the master-version, however substrate uses a private branch with a newer `rocksdb` under it, thus we are compiling with two versions of all these three crates
