### ISSUE TITLE
Extract FIXMEs & TODOs

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/polkadot#139]
We have a bunch of `/// FIXME` and `///TODO` in our code base. In line with our new guideline to only keep them in if they link either to a local ticket or a ticket in a remote repo, let's:

 - [x] collect a list of all remaining non-linked entries in our code base

and for each:
 - [ ] evaluate if they are still relevant
 - [ ] if so, find the relevant ticket or create a new one
 - [ ] evaluate whether that comment should stick in and
 - [ ] either link that ticket
 - [ ] or remove the comment altogether.

**Comment by joepetrowski** [comment]
I can work on this to get familiar with the codebase. For a start:

```
parity@eta ~/p/p/polkadot> grep -rnwie 'FIXME'
service/src/lib.rs:79:	// FIXME: rather than putting this on the config, let's have an actual intermediate setup state
service/src/lib.rs:181:							gossip_duration: Duration::new(4, 0), // FIXME: make this available through chainspec?
target/debug/build/clang-sys-0193c594464aa1ce/out/dynamic.rs:189:            // FIXME: Maybe we can just hardlink or symlink it?

parity@eta ~/p/p/polkadot> grep -rnwie 'TODO'
network/src/consensus.rs:237:		// TODO: propagate statements on a timer?
network/src/lib.rs:146:	// TODO: do this with a cryptographic proof of some kind
network/src/collator_pool.rs:188:			// TODO: punish if not primary?
network/src/collator_pool.rs:208:		// TODO: rearrange periodically to new primary, evaluate based on latency etc.
network/src/tests/consensus.rs:150:		// TODO: send context to worker for message routing.
network/README.adoc:5://TODO Write content :)
src/README.adoc:5://TODO Write content :)
consensus/src/lib.rs:420:						// TODO: https://github.com/paritytech/polkadot/issues/51
consensus/src/lib.rs:762:		// TODO: full re-evaluation
consensus/src/shared_table/mod.rs:141:		// TODO: consider a strategy based on the number of candidate votes as well.
consensus/src/collation.rs:51:	/// Note a bad collator. TODO: take proof
consensus/src/collation.rs:251:		// TODO: https://github.com/paritytech/polkadot/issues/92
consensus/README.adoc:5://TODO Write content :)
scripts/init.sh:11:# TODO: Remove this when fixed.
service/src/chain_spec.rs:57:			code: include_bytes!("../../runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm").to_vec(),	// TODO change
service/README.adoc:5://TODO Write content :)
cli/src/lib.rs:66:	// TODO: make this the full configuration, so embedded nodes don't need
cli/src/lib.rs:140:	// TODO [andre]: timeout this future (https://github.com/paritytech/substrate/issues/1318)
collator/README.adoc:5://TODO Write content :)
executor/README.adoc:5://TODO Write content :)

/// bunch of binaries

runtime/src/parachains.rs:388:	// TODO: Consider integrating if needed.
runtime/README.adoc:5://TODO Write content :)
statement-table/README.adoc:5://TODO Write content :)
Binary file .git/objects/pack/pack-87c9e0fd30a8e4223f79655b23cf0aa423bd8e30.pack matches
primitives/src/lib.rs:61:/// TODO: switch to u32
primitives/src/parachain.rs:142:		// TODO: compare signatures or something more sane
primitives/README.adoc:5://TODO Write content :)
parachain/src/lib.rs:82:// TODO: balance downloads
parachain/src/lib.rs:95:// TODO: egress and balance uploads
parachain/README.adoc:5://TODO Write content :)
```

**Comment by rphmeier** [comment]
> network/src/lib.rs:146:	// TODO: do this with a cryptographic proof of some kind

This has a corresponding issue in Substrate already about cryptographic authentication of validators in the network.

> service/src/lib.rs:79

Likewise; this is something in Substrate.

**Comment by gnunicorn** [comment]
> service/src/lib.rs:79:	// FIXME: rather than putting this on the config, let's have an actual intermediate setup state

so does this: https://github.com/paritytech/substrate/issues/1134

**Comment by joepetrowski** [comment]
Removed the READMEs from the list

- [x] validation/src/lib.rs:420: // TODO: https: //github.com/paritytech/polkadot/issues/51
- [ ] validation/src/lib.rs:762: // TODO: full re-evaluation
- [ ] validation/src/shared_table/mod.rs:141: // TODO: consider a strategy based on the number of candidate votes as well.
- [ ] validation/src/collation.rs:51: /// Note a bad collator. TODO: take proof
- [x] validation/src/collation.rs:251: // TODO: https: //github.com/paritytech/polkadot/issues/92

</br>

- [ ] network/src/lib.rs:146: // TODO: do this with a cryptographic proof of some kind
- [ ] network/src/collator_pool.rs:188: // TODO: punish if not primary?
- [ ] network/src/collator_pool.rs:208: // TODO: rearrange periodically to new primary, evaluate based on latency etc.
- [ ] network/src/validation.rs:237: // TODO: propagate statements on a timer?
- [ ] network/src/tests/validation.rs:150: // TODO: send context to worker for message routing.

</br>

- [ ] scripts/init.sh:11:# TODO: Remove this when fixed.

</br>

- [ ] service/src/chain_spec.rs:57: code: include_bytes!("../../runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm").to_vec(), // TODO change
- [ ] service/src/lib.rs:79: // FIXME: rather than putting this on the config, let's have an actual intermediate setup state
- [ ] service/src/lib.rs:181: gossip_duration: Duration::new(4, 0), // FIXME: make this available through chainspec?

</br>

- [ ] cli/src/lib.rs:66: // TODO: make this the full configuration, so embedded nodes don't need
- [x] cli/src/lib.rs:140: // TODO [andre]: timeout this future (https: //github.com/paritytech/substrate/issues/1318)

</br>

- [ ] runtime/src/parachains.rs:388: // TODO: Consider integrating if needed.

</br>

- [ ] primitives/src/lib.rs:61: /// TODO: switch to u32
- [ ] primitives/src/parachain.rs:142: // TODO: compare signatures or something more sane

</br>

- [ ] parachain/src/lib.rs:82: // TODO: balance downloads
- [ ] parachain/src/lib.rs:95: // TODO: egress and balance uploads

</br>

- [ ] target/debug/build/clang-sys-0193c594464aa1ce/out/dynamic.rs:189: // FIXME: Maybe we can just hardlink or symlink it?
