### ISSUE TITLE
Polkadot v0.8.25 Release checklist

### ISSUE THREAD

**Issue by s3krit** [paritytech/polkadot#1777]
This is the release checklist for Polkadot v0.8.25. **All** following
checks should be completed before publishing a new release of the
Polkadot/Kusama/Westend runtime or client.

### Runtime Releases

The following should be done prior to tagging the potential release. Upon completion, tag the commit and proceed with the All Releases steps.

- [x] Verify [`spec_version`](#spec-version) has been incremented since the
    last release for any native runtimes from any existing use on public
    (non-private/test) networks.
- [x] Verify [new migrations](#new-migrations) complete successfully, and the
    runtime state is correctly updated.
- [x] Verify previously [completed migrations](#old-migrations-removed) are
    removed.
- [x] Verify pallet and [extrinsic ordering](#extrinsic-ordering) has stayed
    the same. Bump `transaction_version` if not.
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for
    [proxy filters](#proxy-filtering).
- [x] Verify [benchmarks](#benchmarks) have been updated for any modified
    runtime logic.
- [x] Verify [Polkadot JS API](#polkadot-js) are up to date with the latest
    runtime changes.

### All Releases

- [x] Check that the new client versions have [run on the network](#burn-in)
    without issue for 12 hours.
- [x] Check that a draft release has been created at
    https://github.com/paritytech/polkadot/releases with relevant [release
    notes](#release-notes)
- [x] Check that [build artifacts](#build-artifacts) have been added to the
    draft-release
- [x] Check that the Cargo.toml version is updated.

### Burn In

Ensure that Parity DevOps has run the new release on Westend, Kusama, and
Polkadot validators for at least 12 hours prior to publishing the release.

### Build Artifacts

Add any necessary assets to the release. They should include:

- Linux binary
- GPG signature of the Linux binary
- SHA256 of binary
- Source code
- Wasm binaries of any runtimes

### Release notes

The release notes should list:

- The priority of the release (i.e., how quickly users should upgrade)
- Which native runtimes and their versions are included
- The proposal hashes of the runtimes as built with
    [srtool](https://gitlab.com/chevdor/srtool)
- Any changes in this release that are still awaiting audit

The release notes may also list:

- Free text at the beginning of the notes mentioning anything important
    regarding this release
- Notable changes (those labelled with B[1-9]-* labels) separated into sections

### Spec Version

A runtime upgrade must bump the spec number. This may follow a pattern with the
client release (e.g. runtime v12 corresponds to v0.8.12, even if the current
runtime is not v11).

### New Migrations

Ensure that any migrations that are required due to storage or logic changes
are included in the `on_runtime_upgrade` function of the appropriate pallets.

### Old Migrations Removed

Any previous `on_runtime_upgrade` functions from old upgrades must be removed
to prevent them from executing a second time.

### Extrinsic Ordering

Offline signing libraries depend on a consistent ordering of call indices and
functions. Compare the metadata of the current and new runtimes and ensure that
the `module index, call index` tuples map to the same set of functions. In case
of a breaking change, increase `transaction_version`.

Note: Adding new functions to the runtime does not constitute a breaking change
as long as they are added to the end of a pallet (i.e., does not break any
other call index).

### Proxy Filtering

The runtime contains proxy filters that map proxy types to allowable calls. If
the new runtime contains any new calls, verify that the proxy filters are up to
date to include them.

### Benchmarks

Run the benchmarking suite with the new runtime and update any function weights
if necessary.

### Polkadot JS

Ensure that a release of [Polkadot JS API](https://github.com/polkadot-js/api/) contains any new types or
interfaces necessary to interact with the new runtime.

**Comment by ordian** [comment]
I remember there were a discussion about using `-rc` suffixes for unreleased versions. 
Does it make sense to tag it as a final release (e.g. v0.8.25) only after burnin is done and everyone is happy?
