### ISSUE TITLE
Polkadot Runtime Parachains Debt Tracking

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#2390]
This PR will serve as an tracker for various technical debt and optimizations that could be made to the Parachains Runtime:

- [ ] Remove multiple parachain offboarding queues: https://github.com/paritytech/polkadot/pull/2360
- [ ] Audit for potential optimizations of append api
- [ ] Remove manual weight tracking from functions
