### ISSUE TITLE
Tracking issue for XCM Revamp

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#2841]
Follow-up issue: #4118

### Priorities
- [x] Harden the `execute_xcm` function against recursion-bombs (https://github.com/paritytech/polkadot/pull/3555, https://github.com/paritytech/polkadot/pull/3586)
- [x] Type-safe wildcard management in `MultiAsset` (https://github.com/paritytech/polkadot/issues/3168).
- [x] Implement proper weight pricing for the queuing and dispatch - it should integrate into the chain's usual transaction weight pricing. (https://github.com/paritytech/polkadot/pull/2896)
- [x] Don't just burn fees - send them somewhere, and test that we get them! (https://github.com/paritytech/polkadot/pull/2896)
- [x] Avoid using `burn` & `mint` in teleport - instead transfer into and out of a special reserved "teleported" account. (https://github.com/paritytech/polkadot/pull/3007)
- [x] Introduce a `reserve_asset_transfer` extrinsic and execution filter enabling it (https://github.com/paritytech/polkadot/pull/3010)
- [x] Add a `register_id` function to paras_registrar (https://github.com/paritytech/polkadot/pull/3008)
- [x] #3168: Typesafe `MultiAsset` wildcards. (https://github.com/paritytech/polkadot/pull/2815)
- [x] #3547: `DepositAsset` and `DepositReserveAsset` should have an extra parameter limiting the number of distinct assets to deposit. (https://github.com/paritytech/polkadot/pull/2815)
- [x] Introduce internal `Vec<Order>` field for `BuyExecution`. (https://github.com/paritytech/polkadot/pull/2815)
- [x] Update XCM format document to reflect new format (https://github.com/paritytech/xcm-format/issues/23).

### Substantial features 
- [x] General `ResponseMap` of `(QueryId, Origin)` -> `EitherOr<Dispatch, Option<Response>>` which allows free execution of the message and then either stores the result or calls a dispatch - in this case it could go overweight be up to the weight of whatever dispatch is in there. It should be added on and checked before executing any further XCMs. (https://github.com/paritytech/polkadot/pull/3629)
- [x] Prepaid outcome reporting mechanism for success/failure. (https://github.com/paritytech/polkadot/pull/3629)
- [x] New instruction `RefundSurplusWeight` which trades surplius weight in and places it back in holding. (https://github.com/paritytech/polkadot/pull/3629)
- [x] `SetErrorHandler` instruction with pre-paid execution of XCM in case of error. (https://github.com/paritytech/polkadot/pull/3629)
- [x] In the case of an incompletely executed XCM, return the weight consumed, not the maximum. (#3629)
- [x] `AssetTrap` instruction which places any remaining assets in the holding account into a special storage item (keyyed under the origin location), even (especially) in the case of error. A secondary XCM instruction `DrainTrap` can fetch those assets and do something with them. A failsafe asset trap could also be in place for the origin. #3694 (#3727)
- [x] XCM Pallet should implement `WrapVersion`. Introduce `QueryVersion` and `NoteVersion` message types, allowing dynamic negotiation of transport version, followed with persistent transport version storage for each origin. (https://github.com/paritytech/polkadot/pull/3736)

### VMP Origins
Figure out how to manage origin permissions. We want root and governance Relay-chain XCM origins to have free execution on the Statemint parachain, but not just random accounts that happen to be instructing the Relay-chain to send an XCM on their behalf to the parachain.
- [x] Introduce `RelayedFrom` XCM (https://github.com/paritytech/polkadot/pull/2865)
- [x] Introduce `RelayedFrom` into `execute_xcm`, checking it's a subconsensus, mutate origin, redispatch; ensure that mutating the origin doesn't create problems for relative locations in e.g. asset descriptors. (https://github.com/paritytech/polkadot/pull/2865)
- [x] Introduce a means of converting a Collective (pallet) `Origin` into a `Plurality` `MultiLocation` - this will likely be through a `Origin` -> `MultiLocation` conversion utility trait. (https://github.com/paritytech/polkadot/pull/2865)
- [x] Introduce XCM sender dispatchable using `RelayedFrom` XCM: (https://github.com/paritytech/polkadot/pull/2865)
  - [x] Introduce an XCM dispatcher into Polkadot, equivalent of xcm-handler in Cumulus, it should allow for `RelayedFrom` messages to be created and sent (search `fn send(origin, dest: MultiLocation`).
  - [x] Use `pallet-xcm` in Cumulus and remove duplicate functionality from `xcm-handler`.
  - [x] Will use the new `Origin` -> `MultiLocation` converter. (https://github.com/paritytech/polkadot/pull/2865)
  - [x] With the `MultiLocation` it should potentially (if non-Null) wrap the XCM in a `Xcm::RelayedFrom`. (https://github.com/paritytech/polkadot/pull/2865)
  - [x] Should be configurable to have a barrier (possibly by just using existing `Origin` -> `MultiLocation` conversion) (https://github.com/paritytech/polkadot/pull/2865)
- [x] Introduce XCM Handler pallet a `Origin::Xcm(MultiLocation)`
- [x] Introduce `ensure_xcm` and `EnsureXcm impl EnsureOrigin` origin barrier and use `EnsureXcm([Parent, Plurality(Executive, >1/2)])` for Admin in Statemint.
- [x] Provide Origin converter to use the `Origin::Xcm` https://github.com/paritytech/polkadot/pull/2896
- [x] Check that `AccountId` origins from Relay have sensible origins on Paras when sent over DMP.

### Queuing
XCMP queueing mechanisms should be largely replicated for VMP queuing.
- [x] UMP outbound queuing.
- [x] UMP inbound queuing & weight limits, similar to DMP (immediate processing, overweight message should not block queue, don't stop processing when one para blocked) (https://github.com/paritytech/polkadot/pull/3575).
- [x] DMP outbound queuing.
- [x] DMP incoming queue & weight limits. (https://github.com/paritytech/cumulus/pull/416)

### Smaller features
- [x] Implement `transfer_asset` for `FungiblesAdapter`, but locate the function in a different trait to avoid the need to implement only when deposit+withdraw are implemented. (https://github.com/paritytech/polkadot/pull/2865)

### Minor refactorings/additions/optimisations
- [x] More tests in xcm-executor/xcm-builder for new logic, especially for `Transact` execution origins (https://github.com/paritytech/polkadot/pull/2948).
- [x] Merge `Filter` and `Contains`. (https://github.com/paritytech/substrate/pull/9514)
- [x] Tests for everything in `xcm-builder` (https://github.com/paritytech/polkadot/pull/2948, https://github.com/paritytech/polkadot/pull/3537).
- [x] Switch to using new `MultiAsset`. (https://github.com/paritytech/polkadot/pull/2815)
- [x] Update Junction when paritytech/parity-scale-codec#262 is done.
- [x] `LocationConversion` should be removed in favour of using the `Convert` trait. (https://github.com/paritytech/polkadot/pull/2836)
- [x] Additional two dispatchables for `fn authorize_upgrade(origin: Root, code_hash: T::Hash)` and `fn enact_authorized_upgrade(origin: Any, code: Vec<u8>)` (https://github.com/paritytech/cumulus/pull/392)
- [x] Introduce `Junctions` separately to `MultiLocation` (https://github.com/paritytech/polkadot/pull/3404)

XCM v3:
- [x] `BurnAsset` instruction.
- [x] `ExpectAsset`, `ExpectOrigin`, `Expect...` instructions.
- [x] Safe version of the `Transact` instruction, allowing version-sensitive dispatching between chains. https://github.com/paritytech/xcm-format/pull/22 (#

Things to consider:
- Message prioritisation/QoS. Currently all messages in a channel must be executed in strict order of being sent. If the receiving system runs out of weight while processing due to a heavy message, then other channels will be tried, even if there are lighter messsages following it which could reasonably be executed. For now this is fine because a) we have an optimised data system for taking only contiguous messages from the beginning of the page stored in state and b) during execution it gives other channels with lighter messages a chance to execute.
- Scheduling. Right now we process all channels' messages, one page at a time in a random-shuffled round-robin, incrementally making more weight available until we have made all weight available and run out of weight to process the next message on every channel. This *works* and is *safe*, but might lead to slightly unexpected stuff happening such as mesages sent much later on a lightly-used channel executing before messages sent on a heavier-used channel.

**Comment by Geek-Lee** [comment]
I can speak？this is try

**Comment by Geek-Lee** [comment]
Stay tuned, come on, dot, hope not to miss this bull market, ride the wind straight.

**Comment by Geek-Lee** [comment]
whenever the roc flies into the sky,
thousands of kilometers will be passed by.

**Comment by Geek-Lee** [comment]
whenever the _dot_ flies into the sky,
thousands of kilometers will be passed by.
