### ISSUE TITLE
Tracking issue for Kusama Parachains Launch

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#2902]
Associated tracking issues:
- XCM: https://github.com/paritytech/polkadot/issues/2841
- Networking: https://github.com/paritytech/polkadot/issues/2888
- Tokens: https://github.com/paritytech/substrate/issues/8453

### Phase 1: Deploy Shell chain
- [x] Finalise Shell/Cumulus
  - [x] Finalise Shell chain runtime
  - [x] Unit tests for all XCM components used in Shell and Kusama Relay
  - [x] Finalise Shell genesis (no tokens)
  - [x] Integrate Shell into Cumulus as runtime
- [x] Finalise Kusama Relay
  - [x] Integrate parachains logic
  - [x] Integrate XCM logic
  - [x] Add XCM-based withdraw+teleport extrinsic usable by signed accounts
- [x] Deploy on and test on Rococo
  - [x] Teleport tokens from Relay
  - [x] Upgrade to standard Test parachain authorised from Relay
- [x] Deploy to Kusama
  - [x] Prepare and release 0.9.0
  - [x] Get validators updated
  - [x] Ascertain sufficient validator interconnectivity & collator accessibility
  - [x] Upgrade runtime
  - [x] Deploy Shell

### Phase 2: Upgrade to Statemint
- [x] Finalise Statemint parachain
  - [x] Tokens pallet
  - [x] XCM logic
  - [x] Genesis (no tokens)
  - [ ] Introduce fees oracle and allow transaction fees to be paid in assets
- [x] Integrate as runtime option in Cumulus
- [x] Deploy and test on Rococo
  - [x] Teleport ROC from Relay
  - [x] Teleport ROC tokens to & from doppelganger
  - [x] Transfer other tokens as reserve from doppelganger
- [x] Upgrade from Shell
- [ ] Enable asset registration

### Phase 3: Begin auctions
- [x] Determine final parameters
- [x] Determine auction schedule
- [x] Publish schedule
- [x] Integrate logic in Kusama Relay
- [x] Deploy logic in Kusama Relay
- [x] Activate auction

**Comment by jzhu1224** [comment]
At what time the auction will start? Thanks.

**Comment by xufuhero** [comment]
It looks like it should start in early June

**Comment by pedja333** [comment]
Parachain auctions are coming (but not soon)

**Comment by czm123github** [comment]
tow month later

**Comment by Samihsia** [comment]
is there a est of the time auction plz

**Comment by OvidiuCode** [comment]
How does this align with what you said: "it is a matter of days rather than weeks to pull the trigger"?
