### ISSUE TITLE
Tracking issue: Pre-checking for PVF Compilation time

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#3211]
We are going to use this issue for tracking progress on the PVF compilation time pre-checking.

- [x] https://github.com/paritytech/substrate/issues/9605
- [x] https://github.com/paritytech/substrate/issues/9606
- [x] https://github.com/paritytech/cumulus/pull/517
- [x] https://github.com/paritytech/polkadot/issues/3720
- [x] https://github.com/paritytech/polkadot/issues/3857
- [x] https://github.com/paritytech/polkadot/issues/4010
- [x] https://github.com/paritytech/polkadot/issues/4009
- [x] #4446
- [x] https://github.com/paritytech/polkadot/pull/4575
- [x] https://github.com/paritytech/polkadot/issues/4610
- [x] https://github.com/paritytech/polkadot/issues/4611
- [x] https://github.com/paritytech/polkadot/pull/4741
- [x] Benchmarks for the paras module logic with PVF pre-checking enabled. (https://github.com/paritytech/polkadot/pull/7138)
- [x] https://github.com/paritytech/polkadot/pull/4683
- [x] #4933
- [x] https://github.com/paritytech/polkadot/pull/4612
- [x] enable PVF pre-checking on Rococo.
- [x] enable PVF pre-checking on Westend.
- [x] enable PVF pre-checking on Kusama.
- [x] enable PVF pre-checking on Polkadot.
- [x] clean-up the code base with the assumption that PVF pre-checking is always on. Adapt the tests that assume PVF pre-checking is true, removing those that only depend on that. (https://github.com/paritytech/polkadot/pull/7138)
- [x] Jump on the next configuration module runtime storage upgrade to remove the configuration field. (https://github.com/paritytech/polkadot/pull/7396)
- [x] https://github.com/paritytech/polkadot/issues/4601 (https://github.com/paritytech/polkadot/pull/7486)
- [ ] finalize the implementor's guide. Remove WIP labels (https://github.com/paritytech/polkadot/pull/7559)

# Original Description

## Problem

If compilation of a Parachain Validation Function (PVF) takes too long or uses too much memory, this can leave a node in limbo as to whether a candidate of that parachain is valid or not. 

The amount of time that a PVF takes to compile is a subjective resource limit and as such PVFs may be maliciously crafted so that there is e.g. a 50/50 split of validators which can and cannot compile and execute the PVF.

This has the following implications:
- In backing, inclusion may be slow due to backing groups being unable to execute the block
- In approval checking, there may be many no-shows, leading to slow finality
- In disputes, neither side may reach supermajority. Nobody will get slashed and the chain will not be reverted or finalized.

As a result of this issue we need a fairly hard guarantee that the PVFs of registered parachains/threads can be compiled within a reasonable amount of time.

## Solution

To have all validators pre-check that the amount of time the validation code takes to compile is under some reasonable limit. Before a parathread can be registered by users, and before a PVF upgrade can be applied by any parathread or chain, the validation code must be signed off on by 2/3 of the current validator set as taking less than some fixed timeout, specified on-chain.

Validators should constantly observe the chain to learn about PVFs which are pending approval, and should acquire and compile these PVFs. They then submit an unsigned transaction in either the affirmative or negative about the PVF. PVFs which don't receive a supermajority of validators attesting to low time taken to compile, within a certain amount of blocks, are discarded. 

When compiling PVFs outside of this check, a much more permissive timeout should be used, and as such the artifact will eventually be compiled and approval checks, dispute votes, etc. will be issued, leading to no stall of the relay chain or of finality.

As a downside, this does mean that every change to the PVF requires additional work to be done by every validator at the time of submission, which means that parathread registration and upgrades should be more expensive / more limited.

## Alternative Solution: Approval Checking

Alternatively, we could have approval checking check that:
  a) the Wasm blob produced by any candidate compiles within a reasonable amount of time
  b) any new Wasm blob registered on-chain by a transaction compiles within a reasonable amount of time

However, there are issues with this solution.

1. it is unclear whether validators that find that either a or b _doesn't_ hold should issue a dispute or not. If they do issue a dispute, then it is possible that they or other validators will be wrongly slashed or the dispute will reach no conclusion.
2. If the validators don't issue a dispute and the block never gets finalized, then the relay chain should be eventually reorganize to avoid the block in question. However, there is nothing in the runtime stopping the offending transaction or pending PVF upgrade from being re-submitted, leading to an infinite cycle of relay chain abandonment.

For these reasons, the initial pre-check should be used.

**Comment by burdges** [comment]
It's tricky.. I've changed my tune somewhat..  

In my mind, approval checking had three advantages:  First, we avoid all validators checking parathread code upgrades, but an alternative would simply be making parathread code upgrades expensive.  Second we're already building a approvals and disputes procedure, so this seems simplest, but yes important differences exist.  We'll also want new validators to join, and for some validators to churn between relay chains when we move towards multiple relay chains, which both require examining our assumptions about the build artifacts caching, so lazy builds sounded nice, but maybe this sucks.

Approval checking would require disputes and slashing since parachains could repeatedly register invalid code until one passed approval checks, which then enables attacks.  Is this worth the risk if everyone needs to build the code eventually anyways and validators all have the storage to cache the artifact?  It's trick but maybe no, so an approval checking design might start parachain code upgrade blocks already escalated.  

As for parathreads, we'll maybe have more confidence in build times but the time we build parathreads, but maybe we just make them pay more for upgrades.  

We've accepted a model where parachain code gets referenced by hash, so multiple code blobs exist simultaneously already.  If parachain code upgrades are special blocks that do not otherwise interact with XCMP, etc., then we need not roll back invalid code upgrades and could merely invalidate the code upgrade.  Yes, this sounds like a big difference from the usual inclusion pipeline.

At some level I think this boils down primarily to slashing:  Are we happy with slashing and forensics for build failures?  If no, then we need escalated build checking, which no longer looks much like approvals.

**Comment by burdges** [comment]
We might leverage the approval's logic for grandpa though:  If a parachain posts a code block then we transport the code to all validators, perhaps via availability and reconstructing, and then all validators build the code.  We then block finality upon build results similarly to blocking finality upon approval votes.  We do not currently know about finality on the relay chain though, so I guess this buys us nothing really.

**Comment by eskimor** [comment]
@slumber There are a few check boxes left, can you make sure they are taken care of please. Thank you!
