### ISSUE TITLE
Tracking issue for Parachain disputes

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#3255]
- [ ] Runtime:
  - [x] Add back relay-chain header signals for reversion
  - [x] Produce inherent containing disputes based on given `InherentData` (#3165)
  - [x] Add a method for going from redundant `InherentData` disputes to needed `MultiDisputeStatementSet` (#3472)
  - [x] Remove disputes module from chains other than Rococo
  - [ ] Implement a slash/reward system which simply logs offenders
  - [x] Deploy to Rococo
  - [ ] Deploy to Westend
  - [ ] Deploy to Kusama
  - [ ] Implement a true slash/reward system (#3161)
- [x] Dispute networking and participation
  - [x] Dispute coordinator (#3150)
  - [x] Dispute participation (#3234) 
  - [x] Dispute distribution guide (#2581)  
  - [x] Provisioner: create `InherenData` with all active disputes (#3165)
  - [x] Dispute distribution implementation (#2581)
  - [x] Ensure that validators notify each other and block authors about disputes in a timely manner
  - [x] Ensure that validators participate in legitimate disputes in a timely manner
- [x] Fork-choice (#3235):
  - [x] Describe in guide
  - [x] Implement fork-choice subsystem
  - [x] Implement custom `SelectChain`
  - [x] Update GRANDPA `VotingRule` to use dispute coordinator DB
  - [x] Use dispute coordinator `DetermineUndisputedChain` in the relay chain selection (https://github.com/paritytech/polkadot/issues/3164)
- [ ] Integration
  - [x] Write an approval-db migration to add the dispute coordinator and fork-choice DBs (#3478)
  - [x] Add the disputes subsystems to the overseer (#3478)
  - [ ] Release a client version containing the disputes subsystems

**Comment by sandreim** [comment]
I think this one can be closed, disputes are live for quite a while.
