### ISSUE TITLE
Benchmark Parachains Runtime: Tracking Issue

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#3850]
This Issue will be used to track end to end benchmarking of the Parachains runtime:

https://github.com/paritytech/polkadot/tree/master/runtime/parachains

- [x] Configuration https://github.com/paritytech/polkadot/pull/3862
- [x] Disputes (not required)
- [x] DMP (not required)
- [x] HRMP: https://github.com/paritytech/polkadot/pull/3876
- [x] Inclusion (not required)
- [x] Initializer #3913
- [x] Paras #3888
- [x] Paras Inherent (https://github.com/paritytech/polkadot/pull/4028)
- [x] Reward Points (not required)
- [x] Scheduler (not required)
- [x] Session Info (not required)
- [x] Shared (not required)
- [x] UMP #3889
- [x] Util (not required)

When checking off an item, please include a PR which includes the benchmark PR.

**Comment by shawntabrizi** [comment]
We are looking for help on this issue, so consider it if you are an external contributor and want to get more involved with benchmarking!

**Comment by hirschenberger** [comment]
> We are looking for help on this issue, so consider it if you are an external contributor and want to get more involved with benchmarking!

I'd like to help, so can I take @KiChjang 's changes as a guide what's to do? Anything that I have to take care of beforehand? So I would start with `Displutes` then.

**Comment by shawntabrizi** [comment]
@hirschenberger happy to have you help. I dont really have a mental model of which pallets are easier than others, so maybe take a look a them and see what you can learn.

The main thing with any benchmarking is:

* reading the pallet and understanding the code
* determining the worst case scenario path for an extrinsic
* creating a benchmark which sets up that worst case scenario, and executes the call
* verifying the final resulting state is what you expect.

https://github.com/paritytech/substrate/tree/master/frame/benchmarking

**Comment by hirschenberger** [comment]
Ok, I read into it and will start with `Dmp`. 

I assume I have to go through some bootstrapping process: 

* Writing the benches
* Compile and run the benches to generate the `weights.rs`
* Add the weights to the exrinsic declarations.
* Commit and the final weigths are generated on the spec-hardware by CI

Is that correct?

**Comment by kianenigma** [comment]
The HRMP is almost done, just needs to fix the inter-pallet calls (which I am not sure with which pattern we're going to manage them -- return weight? or register yourself?), and reviews. The code and benchamarks should be pretty self-explanatory. I'll be away for a week, if someone wants to finish it sooner, by my guest.

**Comment by emostov** [comment]
I am wondering what we should do with inter-pallet calls, as @kianenigma alluded too.

I am working on paras inherents and its rather complex to exhaust all possible code paths for cases with many inter-pallet calls and logic branches. As an example, the below code snippet is from `inclusion::Pallet::enact_candidates`. All users of `enact_candidates` ignore its returned weight. Additionally, the weights from the inter-pallet calls within `enact_candidates` are all just hardcoded DB accesses, which don't include computation time.

https://github.com/paritytech/polkadot/blob/cc24fb87b702db6510d08c689e442b6be384d798/runtime/parachains/src/inclusion.rs#L718-L749

From my current PoV it seems like the benchmarking code would be more maintainable if most inter-pallet calls where benchmarked on their own, but not sure if there are some negative ramifications I have not thought through yet.

I am wondering if others think we should try and weigh these inter pallet functions on their own? And if we do want to do that, should they self-register their weights or always return them to their user?

**Comment by hirschenberger** [comment]
I have a problem in the ump-pallet RP #3889. I want to reuse some functions from the tests module but I can't access them for some reason I don't see. 

See the [here](https://gitlab.parity.io/parity/polkadot/-/jobs/1156080#L533) for the error. Maybe somebody can throw an eye on it and help me?

**Comment by emostov** [comment]
@hirschenberger  from a quick glance I think the issue is that the test module is feature gated with `#[cfg(test)]` and the runtime-benchmarks feature does not compile them. A quick fix would be to change `#[cfg(test)]` to `#[cfg(any(test, feature = "runtime-benchmarks"))]`. I think the better thing to do though would be to pull out the helper functions you want from the test module to some test utils/helper module and feature that  with  `#[cfg(any(test, feature = "runtime-benchmarks"))]`.

**Comment by hirschenberger** [comment]
> @hirschenberger from a quick glance I think the issue is that the test module is feature gated with `#[cfg(test)]` and the runtime-benchmarks feature does not compile them. A quick fix would be to change `#[cfg(test)]` to `#[cfg(any(test, feature = "runtime-benchmarks"))]`. I think the better thing to do though would be to pull out the helper functions you want from the test module to some test utils/helper module and feature that with `#[cfg(any(test, feature = "runtime-benchmarks"))]`.

I thought `runtime-benchmarks` implies `test` because [here](https://github.com/paritytech/polkadot/blob/e5be79ed11a4d3262ffaaf465be734ce3728a5e3/runtime/parachains/src/ump/benchmarking.rs#L32) the `GenesisConfigBuilder` is found in the `tests` module. That's what confuses me.

**Comment by emostov** [comment]
> > @hirschenberger from a quick glance I think the issue is that the test module is feature gated with `#[cfg(test)]` and the runtime-benchmarks feature does not compile them. A quick fix would be to change `#[cfg(test)]` to `#[cfg(any(test, feature = "runtime-benchmarks"))]`. I think the better thing to do though would be to pull out the helper functions you want from the test module to some test utils/helper module and feature that with `#[cfg(any(test, feature = "runtime-benchmarks"))]`.
> 
> I thought `runtime-benchmarks` implies `test` because [here](https://github.com/paritytech/polkadot/blob/e5be79ed11a4d3262ffaaf465be734ce3728a5e3/runtime/parachains/src/ump/benchmarking.rs#L32) the `GenesisConfigBuilder` is found in the `tests` module. That's what confuses me.

So I think that macro, `frame_benchmarking::impl_benchmark_test_suite!`, is only used when the `test` feature is enabled; thus it is alway able to use `GenesisConfigBuilder`. I would suspect all your code compiles when you do `cargo test --features runtime-benchmarks ...` but does not work when you do `cargo run --features runtime-benchmarks`. I will try and take a look myself locally as well

**Comment by hirschenberger** [comment]
@shawntabrizi  #3889 is merged, I think we're done here.
