### ISSUE TITLE
Integration test suite

### ISSUE THREAD

**Issue by drahnr** [paritytech/polkadot#4197]
* [x] Integrate `ZombieNet` https://github.com/paritytech/polkadot/pull/4131
* [x] Expand test spec to provide support for 
  * [x] RPC queries as asserts in test spec
  * [ ] `zipkin` `Span`
  * [x] Add backchannel support of `scale` encoded messages for _coordinate_ or _data dependent_ malicious setups
* [x] Introduce malicious test cases as outline #4131 
  * [ ] More malicious test cases https://github.com/paritytech/polkadot/issues/4776
* [x] Implement crate to use with the backchannel on polkadot (in `/node` dir in the git tree) https://github.com/paritytech/polkadot/pull/4377
* [ ] Assure with devops the individual cluster machines have sufficient power until this can be checked with #4196

**Comment by drahnr** [comment]
CC @pepoviola @ordian @sandreim

**Comment by sandreim** [comment]
A more detailed lists of Zombienet tests that we target to impl: https://github.com/paritytech/polkadot/issues/4776

**Comment by sandreim** [comment]
Closing this one. All remaining work to be done is in https://github.com/paritytech/polkadot/issues/4776
