### ISSUE TITLE
PoC-3 Release (tracking issue)

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#45]
Current Blockers in Substrate:
  - [x] Skipping ahead in GRANDPA sets and rounds: https://github.com/paritytech/substrate/issues/1069
  - [x] Re-enable custom authorship workers in substrate-service: https://github.com/paritytech/substrate/issues/1158

Blockers in Polkadot:
  - [x] Parachain candidates are accompanied with full attestation: #39 
  - [x] GRANDPA integration in runtime: https://github.com/paritytech/polkadot/issues/44
  - [x] Update block authorship to support GRANDPA #37 
  - [x] Allow multiple parachain-attestation sessions to be live at once in network: #40
  - [x] ~~Reintroduce Custom CLI: #43~~
  - [x] Disable dynamic-inclusion in authorship
  - [x] Run GRANDPA voter on all nodes (cc https://github.com/paritytech/substrate/pull/1271)

Testing:
  - Ensure entire test suite passes
  - Ensure GRANDPA and regular set changes are working
  - Deploy and collate for parachains
