### ISSUE TITLE
Refactor into substrate and polkadot-relay

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#51]
Rough gameplan:

- [x] Unpick `native-runtime` from `substrate-executor` (use native `impl_stubs!` macro - current a no-op, to generate the code `|| match method { "execute_block" => safe_call(|| runtime::execute_block(&data.0)),`... and this function, along with the wasm is equates to in as a static-dispatch). (#62)
- [x] Refactor/pick-apart `polkadot-client` into a generic `substrate-client` and a Polkadot-specific `polkadot-client`. (#62)
- [x] Rework `polkadot-rpc` to depend only on the generic (perhaps trait?) `substrate-client` and rename to `substrate-rpc` (and rename `polkadot-rpc-servers` -> `substrate-rpc-servers`). (#62)
- [ ] Rework `polkadot-network` to create a generic substrate module `substrate-network` (the relay-chain sync code plus a peer-network overlay, basically) that can be used by `substrate-client` and extended into a polkadot-specific module `polkadot-network` capable of handling polkadot network messages (parachain candidate selection &c.) and functionality (parachain peer-pre-connections).
- [ ] Consider renaming `substrate::transactions` to `substrate::extrinsics` to reflect the fact that the data is completely generic and may not have features typical of transactions.

**Comment by rphmeier** [comment]
We will also want to reorganize the file hierarchy to put substrate stuff together and apart from polkadot stuff build upon it.

**Comment by rphmeier** [comment]
> Rework polkadot-rpc to depend only on the generic (perhaps trait?) substrate-client and rename to substrate-rpc (and rename polkadot-rpc-servers -> substrate-rpc-servers)

I would address this point differently by setting up a `polkadot-client-api` crate which extracts strongly-typed state information from a `substrate-client` and having the RPC layer depend on that instead.

**Comment by gavofyork** [comment]
agree on the file hierarchy. that can happen once we get `network` refactored into `polkadot-network` and ` substrate-network`.

**Comment by gavofyork** [comment]
also agree on the rpc - it certainly needs a more extensive way of getting information from client. that said, for now it's easy enough to remove any polkadot dependencies from it anyway so it can wait until after we have them split out into different crates (and eventually different repos).
