### ISSUE TITLE
Benchmark Regression Tracking Issue

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#5138]
In https://github.com/paritytech/polkadot/pull/5097, it was shown some benchmarks were not working.

- [x] runtime/kusama/src/weights/frame_system.rs
- [ ] runtime/kusama/src/weights/pallet_collective_council.rs
- [ ] runtime/kusama/src/weights/pallet_collective_technical_committee.rs
- [ ] runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
- [ ] runtime/kusama/src/weights/pallet_elections_phragmen.rs
- [ ] runtime/kusama/src/weights/runtime_common_crowdloan.rs
- [x] runtime/polkadot/src/weights/frame_system.rs
- [ ] runtime/polkadot/src/weights/pallet_collective_council.rs
- [ ] runtime/polkadot/src/weights/pallet_collective_technical_committee.rs
- [ ] runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs
- [ ] runtime/polkadot/src/weights/runtime_common_auctions.rs
- [ ] runtime/polkadot/src/weights/runtime_common_crowdloan.rs
- [ ] runtime/polkadot/src/weights/runtime_common_slots.rs
- [ ] runtime/polkadot/src/weights/runtime_parachains_hrmp.rs
- [x] runtime/westend/src/weights/frame_system.rs
- [ ] runtime/westend/src/weights/pallet_election_provider_multi_phase.rs
- [ ] runtime/westend/src/weights/runtime_common_crowdloan.rs

This issue will track making sure each of these works on the appropriate runtime, and work on a fix if not.

**Comment by shawntabrizi** [comment]
thank you @coderobe

**Comment by ggwpez** [comment]
The `runtime_parachains::ump` benchmark still reports `Invalid input: UnknownMessageIndex`.  
Do you know what that means @hirschenberger? We are currently trying to fix some regressions.  
cc @KiChjang

**Comment by hirschenberger** [comment]
> The `runtime_parachains::ump` benchmark still reports `Invalid input: UnknownMessageIndex`. Do you know what that means @hirschenberger? We are currently trying to fix some regressions. cc @KiChjang

Is it in the `service_overweight` benchmark? It means that the message has not been overweight and was not enqueued to the overweight queue. That might be bc. of some bound-value changes.

So the `create_message_overweight` function may not have produced a overweight message.

Is it urgent? I can have a look on it at the weekend.

**Comment by hirschenberger** [comment]
@ggwpez @shawntabrizi  Ah, we're talking about polkadot benchmarks. 

Ump-benchmarks never worked for polkadot because the polkadot runtime is configured to use a mock `UmpSink`that does not do anything [see here](https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L1227) and [here](https://github.com/paritytech/polkadot/blob/master/runtime/parachains/src/ump.rs#L72).

When I started developing the benchmarks in pre-parachain times, I just skipped polkadot bc. it seemed to me UMP is not ready for primetime in polkadot.

**Comment by shawntabrizi** [comment]
AFAIK this is completed. cc @coderobe
