### ISSUE TITLE
Dispute slashing/hardening

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#6099]
# The Vision

Polkadot is a sharded blockchain. Some validators check some of the parachain blocks. When there's a disagreement about validity of parachain block, a dispute process starts. The checks will escalate to every validator. Once the dispute is resolved, we need to slash and disable validators accordingly to their misbehavior.

# The Plan

- [x] Current-session disputes slashing https://github.com/paritytech/polkadot/pull/5535.
- [ ] Test the limits of the slashing logic in substrate https://github.com/paritytech/polkadot/pull/5978
- [ ] Ensure there are no disputes due to bugs on Kusama https://github.com/paritytech/polkadot/issues/5952
- [ ] Enable slashing on Kusama #5974 
- [ ] Enable slashing on Polkadot
- [ ] Past-session disputes slashing #5947 
- [ ] Validator disabling #5948 
- [ ] Escalate punishment on repeated disputes https://github.com/paritytech/polkadot/issues/5946
- [ ] Enable past-session slashing and disabling on Kusama
- [ ] Enable past-session slashing and disabling on Polkadot

# Open Questions

- [x] There's some consideration about numbers for slashing and correlated slashing: https://github.com/paritytech/polkadot/issues/5898#issuecomment-1221188631.

**Comment by ordian** [comment]
> Now that #5535 is merged, what are the next steps here? Would be good to get them onto the roadmap as well.

Updated the plan.

**Comment by eskimor** [comment]
Closed in favor of (and merged into): https://github.com/paritytech/polkadot/issues/6388 (duplicate).
