### ISSUE TITLE
Async Backing: Update Implementer's Guide for Statement Distribution

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot#6709]
# ISSUE

## Overview

As the title says. 

## Todo

- [x] Add a glossary of terms.
- [x] Some of what I've written so far may be better-suited for module docs instead.
- [x] The legacy v1 page should be preserved (probably on a separate page though?)

**Comment by mrcnski** [comment]
Done in https://github.com/paritytech/polkadot/pull/6738.
