### ISSUE TITLE
PVF worker: separate worker binaries and build with musl

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot#7116]
# ISSUE

## Overview

Per the security/sandboxing work in https://github.com/paritytech/polkadot/issues/4718, we want to separate the PVF worker binaries and build them with musl. There are several advantages in doing this:

- Forcing the use of musl instead of whatever the system C lib is, means we can better control and sandbox the expected syscalls. 
- It is also a win for more deterministic execution, i.e. more homogeneity in execution times and memory used, as opposed to when validators can use different libc's.
- With a separate binary we can always apply LTO optimizations to this binary alone. LTO may make compile times prohibitively long for all of `polkadot`, but the impact on a small binary is much smaller and there may be performance wins. (Related: https://github.com/paritytech/polkadot/issues/4311.)
- With smaller binaries we minimize the risk of [ROP gadgets](https://en.wikipedia.org/wiki/Return-oriented_programming).

## Todo

- [X] move PVF workers into separate binaries
- [X] get cargo to pick up `musl-gcc/++` wrappers.
- [ ] include the binary into `polkadot` executable at build-time (similar to [this](https://github.com/paritytech/substrate/tree/master/utils/wasm-builder))
- [ ] extract the binary at runtime

**Comment by mrcnski** [comment]
Despite my comment at https://github.com/paritytech/polkadot/issues/7099#issuecomment-1519522857, it seems that something like wasm-builder is the only way to embed executables. I had this hack which seemed to work, until I did `cargo clean`:

```rust
const PREPARE_EXE: &'static [u8] =
	include_bytes!(concat!(env!("OUT_DIR"), "/../../../prepare_worker"));
const EXECUTE_EXE: &'static [u8] =
	include_bytes!(concat!(env!("OUT_DIR"), "/../../../execute_worker"));
```

And `env!("CARGO_BIN_EXE_prepare_worker")` only works in integration tests :(. So I will go ahead and implement musl-builder by copy/pasting wasm-builder for now.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/ux-of-distributing-multiple-binaries-take-2/2854/1
