### ISSUE TITLE
Fix probabalistic finality soundness

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#7233]
In Babe we assume probabilistic finality after one session. In fact we do assume this kind of finality in a couple of places elsewhere as well:

# Usages of Probabilistic Finality

## Configuration Changes

We buffer configuration changes and apply them at the [next session](https://github.com/paritytech/polkadot/blob/df61c0bf0834f650e79ddd1a74dea34081ff2b46/runtime/parachains/src/configuration.rs#L19). The logic as described [here](https://github.com/paritytech/polkadot/blob/df61c0bf0834f650e79ddd1a74dea34081ff2b46/runtime/parachains/src/configuration.rs#L1291) ensures that configuration changes are always buffered for at least a full session. Assuming probabilistic finality this ensures that for a given `SessionIndex` you will always get the same configuration.

## Session Information

Similar to configuration, other information like the current validator set, are predetermined a session ahead of time, with the assumption that the set is then indeed uniquely identified by the `SessionIndex`. 

When constructing a `SessionInfo` on a session boundary, we rely on randomness of [one epoch ago](https://github.com/paritytech/polkadot/blob/ccffb736933e21829945d0a1ea662edeef7324e8/runtime/polkadot/src/lib.rs#L1142). This way, assuming probabilistic finality we will always arrive at the same `SessionInfo`.

## Expected PVF existence 

For executing PoVs we assume the PVF to be present on any current chain. This is also based on the assumption of probabilistic finality and is the reason we delay the usage of a PVF for at least one complete session. If this did not hold, validators would not be able to participate in a dispute for example. 

# The Problem

While we allow disputes for a dispute window of 6 sessions, reverting that long is absolutely not sound! For all the reasons noted above and even if you think about the dispute itself: We want to be able to slash validators, now if we just revert long enough we might be forced to revert to a point just before the validator election, with the to be slashed validators not even existing on chain: We would not be able to slash at all! This is just one extreme example to illustrate how bad this really is, but in general the probabilistic finality assumption is backed in quite deeply in a lot of places, if it is broken we lose the ability to reason about the chain.

# Actual Soundness Issues

Now all of this might sound rather theoretical, but we had actual soundness issues in the wild: We found on a test net that signature checks suddenly failed: Signatures by validators became invalid, although they have been valid before! This actually happened with chain reversions on a test network. How was this possible?

1. Due to a dispute we had to revert more than a session worth of blocks.
2. Therefore we alter the history of the previous epoch.
3. We continue producing blocks, session change happens.
4. Then on the next session change, we will use the [randomness from one epoch ago](https://github.com/paritytech/polkadot/blob/ccffb736933e21829945d0a1ea662edeef7324e8/runtime/polkadot/src/lib.rs#L1142) to initialize the next session, but we altered that previous epoch! Therefore we will arrive at a different `SessionInfo`, with a differently (shuffled) validator set then the last time we entered that session.
5. When retrieving keys from the session info, we will pick different ones and signature checks fail.

Granted given the long session time we have on production network, this is unlikely to ever happen in production. But with chain reversions it is actually possible, assuming some issue or an attack: An attacker can make us lose soundness, by just DoSing long enough. Where the time needed is exactly known in advance - only one hour on Kusama!

The question is, can we do better? Indeed we can: We can make the issue less severe and trade soundness for liveness, which is a good deal in general, but in this particular case even more so:

# Solution

## Problem Statement

Losing soundness due to some bug or an attack is not a good position to be in. What can we do about it? First we have to realize the prerequisites:

1. A very long finality stall, where block production already severely slowed down (1 block per hour on production networks).
2. A chain reversion due to a dispute, which reverts a complete session.

If you consider (1) you will realize that we already have a liveness issue: Block production already slowed down a lot, so reverting a session worth of block for example would not actually be that much reverted work and this already leads to the solution I am proposing:

We assume probabilistic finality after one session, yet we allow chain reversions of a larger depth - essentially ruining our probabilistic finality assumption. So what can we do about it?

We need to ensure it holds.

Let's assume the following situation:

```

                             Session N                           N + 1
------------------------------^--|--------------------------------!|------------------------------------
                current safe reversion point
```                   
                   
The ^ marks the longest chain that can be assume "reversion safe", for now let's assume this is the same as finality as in GRANDPA. 

Now what property do we need to maintain? Once we are in session `N` (past the first `|`) we would be using e.g. randomness and configurations set in session `N - 1` for creating session `N + 1`. Session `N` is not affected directly by session `N - 1`. Hence it is safe to start producing blocks in session `N`, even though we might end up reverting back into session `N - 1`. What would not be safe, if we were already in session `N + 1` and reverted back to session `N - 1` as then the randomness of session `N - 1` and configuration would have been used already. If we reverted then, different randomness would be used. In other words, it is safe to revert a session boundary, it is not safe to revert two or again put differently: We cannot revert _more_ than a complete session.

In the above illustration, the current safe reversion point is in session `N-1`, this means crossing the session boundary on `N+1` marked with the exclamation mark `!` is not safe! Hence we should not! But session changes are determined based on time. So how can we not move to the next session? The answer is, we can not, we have to do the session change, but we can do it in a way that is safe!

If we find our self in the situation that the child of the current block would already be in session `N+1`, but our current safe reversion point is still in session `N-1`, we need to build that child block on our current safe reversion point! In other words, before entering session `N+1` we have to ensure that there does not exist any block that could be later on reverted due to a dispute, we do that via a preemptive reversion to our safe point, resulting in:

```
                         Session N              N + 1
-------------------------------^|                -|-
                current safe reversion point
```

Assuming finality is still halted, this can continue to happen again and again. Everytime we would become unsound, we revert and by this maintaining soundness. If you look closely at the previous graph you will notice that the chain is still progressing:

## Ensuring Chain Progress / Liveness Considerations

Early reversion might sound problematic from a liveness perspective, but is actually less of a problem as it might appear initially. First as mentioned previously, with such a long finality stall block production will be _very_ slow, so the actual amount of work being reverted is not that much. Second, the reversion technique still guarantees that the chain will make progress. In particular it is ensured that the chain is making at least one block per session.

This is, because the current safe reversion point is in fact not just the finalized chain, but any tip of the chain which only contains blocks which are either finalized or empty as far as parachain consensus is concerned: If there are no candidates included in a chain, it can also never reverted by a dispute. This means if we revert back to our current safe reversion point, the block that is being built on top of it will be empty (from the perspective of parachains) and thus our current safe reversion point advanced one block.

## Session Changes on Reversion

If you look at the above graphs, you will realize that the block being built on top of the current safe point will be still in session `N-1` in parachain consensus. This is because we predetermine the session of the next block in advance. The new session change to session `N` will happen in the next block. More details are very relevant to completely reason about this, [inquiry pending](https://substrate.stackexchange.com/questions/8498/session-changes-on-reversion).

## Implementation Considerations

Depending on what we will learn [here](https://substrate.stackexchange.com/questions/8498/session-changes-on-reversion), the suggested logic should be implementable purely on the node side. No runtime changes should be needed. Argument for the base case (argument for repeated reversions following, once question on session changes is resolved):

The decision to revert happens right at the session change to session `N + 1`, based on the finality state at the session boundary to session `N` ... so a full session away. It is reasonable to expect a super majority to be in sync on the finality state of a block that old. More importantly, assuming finality is actually lagging that much, it is impossible for any honest node to come to the conclusion that it is fine to continue building on that chain, as the needed finality votes don't exist! Nor would any honest node import such a block, hence for all intents and purposes such a soundness breaking block can not exist with this reversion rule in place.

The worst case for a node side implementation would be that finality is catching up exactly at the time where we decide to revert, resulting in a race. We will definitely need to check that the reversion logic handles the case well: If a reverted chain gets finalized, the reversion should be ignored. For this argument let's assume this is the case, what scenarios can occur:

1. Super majority already reverted at the time of reaching finality and alternative fork already exists.
2. Less than 1/3 of the nodes already reverted at the time of reaching finality.
3. greater 1/3 and  less than 2/3 of the nodes already reverted at the time of reaching finality.

In all those cases, including the worst case (1), things should work out just fine if finality takes precedence over reversion. The fork  based on the reverted chain will simply get abandoned, because if fell behind finality.

# Implementation Steps

- [ ] Make sure finality trumps reversion
- [ ] Keep track of current safe reversion points: Finalized chain + blocks not including any candidates.
- [ ] Change chain selection rule to take into account current safe reversion points. If for the current fort it is in the previous session: revert if `session_index_for_child()` indicates another session change. It is important to do this race free before authoring a block. E.g. just having the dispute coordinator send [`RevertBlocks`](https://github.com/paritytech/polkadot/blob/ae96e09e6ad1810b8d04d4530c07173e604a763d/node/subsystem-types/src/messages.rs#L523), would be insufficient as if that message ran late, we could still be producing that unsound block.

**Comment by burdges** [comment]
As @AlistairStewart and I both said before, we should never reduce the number of blocks in an epoch, but instead either (a) make header only blocks, or else (b) make epochs last longer but have the same number of blocks.

We should discuss if we need consensus to add time between blocks ala (b).  We could anyways provide finality on-chain using beefy, so then block rate gets determines by when we last put on-chain some beefy finality proof.  We do not afaik need consensus for (a) meaning we make header only blocks ourselves and do not build on blocks with bodies.

Aside from auto reversion, we've several bad soundness solutions:
1. Assume finality never stalls for more than an epoch.  It's historically an unsupported assumption, so it's unsound.
2. Assume governance fixes any soundness errors a long finality stall causes.  Very nasty, but maybe doable.   
3. We disable parachains and lock finality until governance either manually approves and advance finality, or manually reverts, possibly slashing.  Actually doable, but I suspect result match auto-reversion, just more annoying.

We do have one other viable seemingly soundness solution:
4. All validators should've escalated any parablock that blocks us.  We should thus make progress in approvals eventually, even if not in grandpa due to other issues.  We've possibly escalated every parablock of course, so we need enough free CPU cycles and bandwidth, but doing this sounds plausible under (a) or (b) . 

Auto reversion sounds much easier to analyze, and minimizes unused code paths, but (4) sounds nicer politically.

**Comment by eskimor** [comment]
> As @AlistairStewart and I both said before, we should never reduce the number of blocks in an epoch, but instead either (a) make header only blocks, or else (b) make epochs last longer but have the same number of blocks.

But we are doing this already: This is how reverts work. The blocks already exist, we cannot make them empty after the fact.

**Comment by burdges** [comment]
Yes of course, given reverts have a higher priority, but yes we should be careful about how cheap reverts become elsewhere.
