### ISSUE TITLE
[meta] strict on-runtime-upgrade CI checks to prevent accidental runtime upgrade breakages

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot#7430]
`try-runtime-cli` `on-runtime-upgrade` has stabilised over the last few months to that point where we can add CI checks to ensure Polkadot & Substrate PRs don't accidentally break upcoming polkadot/kusama/rococo/westend runtime upgrades

Creating a meta issue to track this progress.

Remaining TODOs:
- [ ] Fix existing migration issues
  - [ ] https://github.com/paritytech/substrate/pull/14421
- [ ] Update polkadot CI to run on-runtime-upgrade on every polkadot PR https://github.com/paritytech/polkadot/pull/7422
- [ ] Merge https://github.com/paritytech/substrate/pull/14311
- [ ] Implement `VersionedRuntimeUpgrade` for `Unreleased` pallet migrations
- [ ] Add a check to substrate CI that will fail if a companion needs to be written to prevent runtime migration breakage

After some time has passed and we are confident in the robustness of the CI checks...
- [ ] Block merging until on-runtime-upgrade checks are green
