### ISSUE TITLE
Fix fallout after removing Polkadot & Kusama native runtimes

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot#7468]
After [this](https://github.com/paritytech/polkadot/pull/7467) pull request got merged, the polkadot node will not depend on the Polkadot & Kusama native runtimes anymore. This brings some substantial changes with it, that may lead to more complicated usage for things like benchmarking etc.

As the node will not be able to provide things like the Polkadot and Kusama dev chain specs we should add some tool to the fellowship repo to generate these chain specs. Things `block overhead` and `benchmark extrinsic` will also not work anymore as they rely on the native runtime.

Certain tools like `staking-miner`/`generate-bags` still depend on the native runtime of Kusama/Polkadot. They will also need to be rewritten in a way to get rid off the native runtime.

```[tasklist]
### Tasks
- [ ] Write a tool to generate the chain specs in the fellowship repo
- [ ] Move benchmarking stuff over to use a runtime api for constructing the benchmarking data
- [ ] Move existing tooling (staking-miner, generate-bags) to use a runtime api/subxt
```

**Comment by bkchr** [comment]
Apparently staking-miner with subxt already exists :) https://github.com/paritytech/staking-miner-v2
